pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'chaddekiran/bookmycar_backend'
        DOCKER_TAG = "v1.0.${env.BUILD_NUMBER}"
        
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ChaddeKiran/BookMyCar.git',
                    credentialsId: 'GITHUB_CRED'
            }
        }

        stage('Install') {
            steps {
                dir('backend') {
                    sh './mvnw clean install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh '''
                        docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                        docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
                    '''
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'DOCKER_CRED',
                    usernameVariable: 'DOCKER_USERNAME',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh '''
                        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                        docker push ${DOCKER_IMAGE}:latest
                    '''
                }
            }
        }

        stage('Deployment to EKS') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'AWS_CRED'
                ]]) {
                    sh """
                        aws eks --region ${AWS_REGION} update-kubeconfig --name ${EKS_CLUSTER_NAME}
                        
                        kubectl apply -f prod/deployments/deployment-blue.yaml
                        
                        kubectl set image deployment/bookmycar-backend \
                        backend=${DOCKER_IMAGE}:${DOCKER_TAG} \
                        --namespace=prod
                    """
                }
            }
        }
    }

    post {
        always {
            sh '''
                docker rmi ${DOCKER_IMAGE}:${DOCKER_TAG} || true
                docker rmi ${DOCKER_IMAGE}:latest || true
            '''
        }
        success {
            echo 'Deployment to EKS succeeded!'
        }
        failure {
            echo 'Pipeline failed. Check logs above.'
        }
    }
}