apiVersion: v1
kind: Service
metadata:
  name: bookmycar-backend
  namespace: prod
spec:
  selector:
    app: bookmycar-backend
    version: blue  # Change to 'green' to switch to green deployment
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  type: ClusterIP