apiVersion: v1
kind: ConfigMap
metadata:
  name: bookmycar-configmap
  namespace: prod
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://bookmycar-mysql:3306/bookmycar_db"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "admin"
  SPRING_PROFILES_ACTIVE: "prod"